### ISSUE TITLE
Add intrinsic size to the generated image

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/jekyll-cloudinary#44]
Prevents page rendering jank

See https://codepen.io/eeeps/pen/qLKwEZ
Example: https://github.com/v8/v8.dev/pull/144/files

**Comment by nhoizey** [comment]
Maybe add a `--aspect-ratio` inline style right now:
https://css-tricks.com/aspect-ratio-boxes/#article-header-id-7

```css
[style*="--aspect-ratio"] > :first-child {
  width: 100%;
}
[style*="--aspect-ratio"] > img {
  height: auto;
}
@supports (--custom: property) {
  [style*="--aspect-ratio"] {
    position: relative;
  }
  [style*="--aspect-ratio"]::before {
    content: "";
    display: block;
    padding-bottom: calc(100% / (var(--aspect-ratio)));
    height: 0;
    overflow: hidden;
  }
  [style*="--aspect-ratio"] > :first-child {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
  }
}
```
