### ISSUE TITLE
Couldn't find this image to check its width:

### ISSUE THREAD

**Issue by k16e-me** [nhoizey/jekyll-cloudinary#51]
Hi, I have set `verbose: false` even explicitly. And I imagine that the call for the image happens to Cloudinary, not from my project folder, but still for every image I call, I get this error:

```
[Cloudinary] Couldn't find this image to check its width: /Users/kbmac/Documents/Sites/kom_v1/_pages/home_hero_i4mius.jpg.
       [Cloudinary] Couldn't find this image to check its width: /Users/kbmac/Documents/Sites/kom_v1/./home_hero_i4mius.jpg.
```

```
cloudinary:
  cloud_name: cholita
  verbose: false
  origin_url: 'https://res.cloudinary.com/cholita/image/upload/'
  presets:
    default:
      min_width: 576
      max_width: 1920
      fallback_max_width: 1024
      steps: 4
```

![image](https://user-images.githubusercontent.com/52034326/59965243-59782f80-9503-11e9-9718-d02246819ca0.png)
